### PR TITLE
Use server-side templating to render HTML

### PR DESCRIPTION
**Pull request by starcalibre**
As discussed Monday, this PR adds the server-side templating using ``Jinja2``. 

* Larger HTML files have been broken down into smaller files
* Screens are now presented in a table instead of a dropdown menu
* Some JS was updated to play nicely with the new templating
* HTML will be minified when the UI is started in "production" mode.

### CODE REVIEW

**Comment by starcalibre** [comment]
@jni this should be good to go :)

**Comment by jni** [comment]
@starcalibre added a few more comments. Also, can you comment on the feasibility of live-loading a dataset (without spinners)? (Obvs doesn't have to happen now, just want to know if it's possible, and if so, add an issue so that we remember to do it at some point.)

**Comment by starcalibre** [comment]
@jni I'm sure it's possible. The flask docs give an [example](http://flask.pocoo.org/docs/0.10/patterns/streaming/) of using a generator to send a CSV line-by-line as a series of responses. I don't see why such a pattern couldn't be adapted to a Mongo cursor.. 

We already have issue #47 for improving the initial load times and process, I'll add a comment there. :)

**Comment by jni** [comment]
@starcalibre LOL, it's already one of the points in that issue. =)

**Comment by starcalibre** [comment]
@jni Happy new year! Should be good to go now..!

**Comment by jni** [comment]
And a very happy new year to you, sir! =)

**Pull request merged**
